# Adopted from bevy
# See <https://github.com/bevyengine/bevy/blob/main/deny.toml>

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = [
  "MIT",
  "MIT-0",
  "Apache-2.0",
  "0BSD",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "ISC",
  "Zlib",
  "CC0-1.0",
  "OFL-1.1",
]
exceptions = [
  { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
]
default = "deny"

[bans]
multiple-versions = "deny"
# TODO: Change back to "deny"
# This currently doesn't work with git dependencies (even if the hash is fixed)
# See <https://github.com/Leafwing-Studios/Emergence/issues/193>
wildcards = "warn"
highlight = "all"

skip = [
  { name = "concurrent-queue", version = "1.2.4" }, # from bevy_tasks

  # below are from bevy 0.9.1 > bevy_winit 0.9.1 > winit 0.27.5

  { name = "raw-window-handle", version = "0.4.3" }, # from winit 0.27.5
  { name = "windows-sys", version = "0.36.1" }, # from winit 0.27.5
  { name = "windows_aarch64_msvc", version = "0.36.1" }, # from windows-sys - 0.36.1
  { name = "windows_x86_64_gnu", version = "0.36.1" }, # from windows-sys - 0.36.1
  { name = "windows_i686_msvc", version = "0.36.1" }, # from windows-sys - 0.36.1
  { name = "windows_x86_64_gnu", version = "0.36.1" }, # from windows-sys - 0.36.1
  { name = "windows_x86_64_msvc", version = "0.36.1" }, # from windows-sys - 0.36.1


]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# If you add something here please also add a comment explaining why it's necessary :)
allow-git = []