# Based on https://github.com/Leafwing-Studios/Emergence

[package]
name = "ci"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
xshell = "0.2"
bitflags = "1.3"